### ISSUE TITLE
sprig reset button 

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig-hax#3]
the sprig's pi pico lacks a reset button. it would be really useful to have some sort of modification to facilitate resetting- sort of like [pimonori's captain resetti](https://shop.pimoroni.com/en-us/products/captain-resetti-pico-reset-button). however, captain resetti is no longer sold, and is designed for the pico, not the pico H or pico WH.

**Comment by opticaldrive** [comment]
Done in #5
